language: node_js
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift
node_js:
  - 0.11
  - 0.10